// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvF4MW3P3SiPk5fqNqcUfU4QqEwquDXr0',
    appId: '1:278085570300:web:27688f10e696f3b2265179',
    messagingSenderId: '278085570300',
    projectId: 'instagram-clone-57b94',
    authDomain: 'instagram-clone-57b94.firebaseapp.com',
    storageBucket: 'instagram-clone-57b94.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCChm7918j_i-4ZRVrBxm-HK7wlXKIHM9c',
    appId: '1:278085570300:android:d92fa92e5344ba1e265179',
    messagingSenderId: '278085570300',
    projectId: 'instagram-clone-57b94',
    storageBucket: 'instagram-clone-57b94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjPPgWX3I8yU3-3bfd3q2MZYSOmW-iexM',
    appId: '1:278085570300:ios:d09e0dbc47a686c3265179',
    messagingSenderId: '278085570300',
    projectId: 'instagram-clone-57b94',
    storageBucket: 'instagram-clone-57b94.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjPPgWX3I8yU3-3bfd3q2MZYSOmW-iexM',
    appId: '1:278085570300:ios:d09e0dbc47a686c3265179',
    messagingSenderId: '278085570300',
    projectId: 'instagram-clone-57b94',
    storageBucket: 'instagram-clone-57b94.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClKt2TDlyihVv1uz43rZjntGmRCZmeLSU',
    appId: '1:278085570300:web:24aa19c88fadc984265179',
    messagingSenderId: '278085570300',
    projectId: 'instagram-clone-57b94',
    authDomain: 'instagram-clone-57b94.firebaseapp.com',
    storageBucket: 'instagram-clone-57b94.appspot.com',
  );
}

/*
make a er diagram in image were
1 user view products
2 user view Product details
3 user can add to cart or buy the product
4 if added to cart go to modifiy product quantity 
5 next go for check out 
6 in checkout can apply discount coupons
7 payment method 
8 payment successfull go to the orders section 
9 view order details 
10 modify order details

*/